arm_controller_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - J1_A
    - J2_A
    - J3_A
    - J4_A
    - J5_A
    - J6_A
  gains:
    J1_A:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J2_A:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J3_A:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J4_A:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J5_A:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    J6_A:
      p: 100
      d: 1
      i: 1
      i_clamp: 1