controller_list:
  - name: concert_controller_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - J1_E
      - J2_E
      - J3_E
      - J4_E
      - J5_E
      - J6_E