controller_list:
  - name: fake_concert_controller_controller
    type: $(arg fake_execution_type)
    joints:
      - J1_E
      - J2_E
      - J3_E
      - J4_E
      - J5_E
      - J6_E
initial:  # Define initial robot poses per group
  - group: concert_controller
    pose: home